"""initial schema

Revision ID: 8a9f75265128
Revises:
Create Date: 2026-10-02 18:05:17.044077

Hand-written (not autogenerated — no live database was available in this
environment at authoring time). Mirrors revenueflowai.models exactly;
re-run `alembic check` / a diff against a live DB before relying on this.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql as pg

revision: str = "8a9f75265128"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

MONEY = sa.Numeric(18, 4)
QUANTITY = sa.Numeric(18, 4)


def _timestamps():
    return [
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    ]


def _scoped_columns():
    """Common columns on every ingested business record: scope + lineage."""
    return [
        sa.Column("organization_id", pg.UUID(as_uuid=True), sa.ForeignKey("organizations.id"), nullable=False),
        sa.Column("business_unit_id", pg.UUID(as_uuid=True), sa.ForeignKey("business_units.id"), nullable=False),
        sa.Column("dataset_version_id", pg.UUID(as_uuid=True), sa.ForeignKey("dataset_versions.id"), nullable=False),
        sa.Column("external_id", sa.String(128), nullable=False),
        sa.Column("import_job_id", pg.UUID(as_uuid=True), sa.ForeignKey("import_jobs.id"), nullable=False),
        sa.Column("source_filename", sa.String(256), nullable=False),
        sa.Column("source_row_number", sa.Integer(), nullable=False),
    ]


def _create_scoped_table(name: str, *extra_columns: sa.Column) -> None:
    op.create_table(
        name,
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True),
        *_timestamps(),
        *_scoped_columns(),
        *extra_columns,
    )
    op.create_index(f"ix_{name}_organization_id", name, ["organization_id"])
    op.create_index(f"ix_{name}_business_unit_id", name, ["business_unit_id"])
    op.create_index(f"ix_{name}_dataset_version_id", name, ["dataset_version_id"])
    op.create_index(f"ix_{name}_external_id", name, ["external_id"])


def upgrade() -> None:
    # --- Tenancy ---
    op.create_table(
        "organizations",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True),
        *_timestamps(),
        sa.Column("name", sa.String(256), nullable=False, unique=True),
        sa.Column("slug", sa.String(128), nullable=False, unique=True),
    )

    op.create_table(
        "business_units",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True),
        *_timestamps(),
        sa.Column("organization_id", pg.UUID(as_uuid=True), sa.ForeignKey("organizations.id"), nullable=False),
        sa.Column("code", sa.String(64), nullable=False),
        sa.Column("name", sa.String(256), nullable=False),
        sa.UniqueConstraint("organization_id", "code", name="uq_business_unit_org_code"),
    )
    op.create_index("ix_business_units_organization_id", "business_units", ["organization_id"])

    op.create_table(
        "app_users",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True),
        *_timestamps(),
        sa.Column("oidc_subject", sa.String(256), nullable=False, unique=True),
        sa.Column("email", sa.String(320), nullable=False, unique=True),
        sa.Column("display_name", sa.String(256), nullable=False),
        sa.Column("role", sa.String(32), nullable=False),
        sa.Column("organization_id", pg.UUID(as_uuid=True), sa.ForeignKey("organizations.id"), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    op.create_index("ix_app_users_oidc_subject", "app_users", ["oidc_subject"])
    op.create_index("ix_app_users_organization_id", "app_users", ["organization_id"])

    op.create_table(
        "user_business_unit_grants",
        sa.Column("user_id", pg.UUID(as_uuid=True), sa.ForeignKey("app_users.id"), primary_key=True),
        sa.Column("business_unit_id", pg.UUID(as_uuid=True), sa.ForeignKey("business_units.id"), primary_key=True),
    )

    # --- Ingestion / lineage (import_jobs and dataset_versions reference each
    # other; create import_jobs without the forward FK, add it after). ---
    op.create_table(
        "import_jobs",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True),
        *_timestamps(),
        sa.Column("organization_id", pg.UUID(as_uuid=True), sa.ForeignKey("organizations.id"), nullable=False),
        sa.Column("business_unit_id", pg.UUID(as_uuid=True), sa.ForeignKey("business_units.id"), nullable=False),
        sa.Column("created_by_user_id", pg.UUID(as_uuid=True), sa.ForeignKey("app_users.id"), nullable=False),
        sa.Column("idempotency_key", sa.String(128), nullable=False),
        sa.Column("bundle_hash", sa.String(64), nullable=False),
        sa.Column("status", sa.String(32), nullable=False, server_default="queued"),
        sa.Column("error_code", sa.String(64), nullable=True),
        sa.Column("error_detail", sa.JSON(), nullable=True),
        sa.Column("lease_owner", sa.String(128), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("activated_dataset_version_id", pg.UUID(as_uuid=True), nullable=True),
        sa.Column("validation_summary", sa.JSON(), nullable=True),
        sa.UniqueConstraint("organization_id", "idempotency_key", name="uq_import_job_idempotency"),
    )
    op.create_index("ix_import_jobs_organization_id", "import_jobs", ["organization_id"])
    op.create_index("ix_import_jobs_business_unit_id", "import_jobs", ["business_unit_id"])
    op.create_index("ix_import_jobs_bundle_hash", "import_jobs", ["bundle_hash"])

    op.create_table(
        "dataset_versions",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True),
        *_timestamps(),
        sa.Column("organization_id", pg.UUID(as_uuid=True), sa.ForeignKey("organizations.id"), nullable=False),
        sa.Column("business_unit_id", pg.UUID(as_uuid=True), sa.ForeignKey("business_units.id"), nullable=False),
        sa.Column("source_import_job_id", pg.UUID(as_uuid=True), sa.ForeignKey("import_jobs.id"), nullable=False),
        sa.Column("snapshot_date", sa.Date(), nullable=False),
        sa.Column("activated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("superseded_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index("ix_dataset_versions_organization_id", "dataset_versions", ["organization_id"])
    op.create_index("ix_dataset_versions_business_unit_id", "dataset_versions", ["business_unit_id"])

    op.create_foreign_key(
        "fk_import_jobs_activated_dataset_version_id",
        "import_jobs",
        "dataset_versions",
        ["activated_dataset_version_id"],
        ["id"],
    )

    op.create_table(
        "import_job_files",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True),
        *_timestamps(),
        sa.Column("import_job_id", pg.UUID(as_uuid=True), sa.ForeignKey("import_jobs.id"), nullable=False),
        sa.Column("filename", sa.String(256), nullable=False),
        sa.Column("object_key", sa.String(512), nullable=False),
        sa.Column("file_hash", sa.String(64), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=True),
        sa.Column("byte_size", sa.Integer(), nullable=False),
    )
    op.create_index("ix_import_job_files_import_job_id", "import_job_files", ["import_job_id"])

    op.create_table(
        "audit_events",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("actor_user_id", pg.UUID(as_uuid=True), sa.ForeignKey("app_users.id"), nullable=True),
        sa.Column("organization_id", pg.UUID(as_uuid=True), sa.ForeignKey("organizations.id"), nullable=False),
        sa.Column("event_type", sa.String(64), nullable=False),
        sa.Column("outcome", sa.String(32), nullable=False),
        sa.Column("subject_type", sa.String(64), nullable=True),
        sa.Column("subject_id", sa.String(128), nullable=True),
        sa.Column("detail", sa.JSON(), nullable=True),
    )
    op.create_index("ix_audit_events_organization_id", "audit_events", ["organization_id"])
    op.create_index("ix_audit_events_event_type", "audit_events", ["event_type"])

    # --- Order-to-Cash domain entities ---
    _create_scoped_table(
        "customers",
        sa.Column("account_number", sa.String(64), nullable=True),
        sa.Column("customer_name", sa.String(256), nullable=False),
        sa.Column("payment_terms_days", sa.Integer(), nullable=True),
    )

    _create_scoped_table(
        "orders",
        sa.Column("customer_external_id", sa.String(128), nullable=False),
        sa.Column("order_date", sa.Date(), nullable=False),
        sa.Column("currency", sa.String(3), nullable=False),
        sa.Column("status", sa.String(32), nullable=False),
        sa.Column("promised_ship_date", sa.Date(), nullable=True),
    )
    op.create_index("ix_orders_customer_external_id", "orders", ["customer_external_id"])

    _create_scoped_table(
        "order_lines",
        sa.Column("order_external_id", sa.String(128), nullable=False),
        sa.Column("item_code", sa.String(128), nullable=False),
        sa.Column("ordered_quantity", QUANTITY, nullable=False),
        sa.Column("cancelled_quantity", QUANTITY, nullable=False, server_default="0"),
        sa.Column("unit_price", MONEY, nullable=False),
        sa.Column("line_amount", MONEY, nullable=False),
    )
    op.create_index("ix_order_lines_order_external_id", "order_lines", ["order_external_id"])

    _create_scoped_table(
        "shipments",
        sa.Column("order_external_id", sa.String(128), nullable=False),
        sa.Column("shipment_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(32), nullable=False),
        sa.Column("delivery_date", sa.Date(), nullable=True),
    )
    op.create_index("ix_shipments_order_external_id", "shipments", ["order_external_id"])

    _create_scoped_table(
        "shipment_lines",
        sa.Column("shipment_external_id", sa.String(128), nullable=False),
        sa.Column("order_line_external_id", sa.String(128), nullable=True),
        sa.Column("shipped_quantity", QUANTITY, nullable=False),
    )
    op.create_index("ix_shipment_lines_shipment_external_id", "shipment_lines", ["shipment_external_id"])
    op.create_index("ix_shipment_lines_order_line_external_id", "shipment_lines", ["order_line_external_id"])

    _create_scoped_table(
        "invoices",
        sa.Column("customer_external_id", sa.String(128), nullable=False),
        sa.Column("order_external_id", sa.String(128), nullable=True),
        sa.Column("invoice_date", sa.Date(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("currency", sa.String(3), nullable=False),
        sa.Column("invoice_amount", MONEY, nullable=False),
        sa.Column("status", sa.String(32), nullable=False),
    )
    op.create_index("ix_invoices_customer_external_id", "invoices", ["customer_external_id"])
    op.create_index("ix_invoices_order_external_id", "invoices", ["order_external_id"])

    _create_scoped_table(
        "invoice_lines",
        sa.Column("invoice_external_id", sa.String(128), nullable=False),
        sa.Column("order_line_external_id", sa.String(128), nullable=True),
        sa.Column("shipment_line_external_id", sa.String(128), nullable=True),
        sa.Column("billed_quantity", QUANTITY, nullable=True),
        sa.Column("line_amount", MONEY, nullable=False),
    )
    op.create_index("ix_invoice_lines_invoice_external_id", "invoice_lines", ["invoice_external_id"])
    op.create_index("ix_invoice_lines_order_line_external_id", "invoice_lines", ["order_line_external_id"])
    op.create_index("ix_invoice_lines_shipment_line_external_id", "invoice_lines", ["shipment_line_external_id"])

    _create_scoped_table(
        "receipts",
        sa.Column("customer_external_id", sa.String(128), nullable=False),
        sa.Column("receipt_date", sa.Date(), nullable=False),
        sa.Column("currency", sa.String(3), nullable=False),
        sa.Column("receipt_amount", MONEY, nullable=False),
        sa.Column("status", sa.String(32), nullable=False),
        sa.Column("remittance_reference", sa.String(256), nullable=True),
    )
    op.create_index("ix_receipts_customer_external_id", "receipts", ["customer_external_id"])

    _create_scoped_table(
        "receipt_applications",
        sa.Column("receipt_external_id", sa.String(128), nullable=False),
        sa.Column("invoice_external_id", sa.String(128), nullable=False),
        sa.Column("applied_amount", MONEY, nullable=False),
        sa.Column("application_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(32), nullable=False),
    )
    op.create_index("ix_receipt_applications_receipt_external_id", "receipt_applications", ["receipt_external_id"])
    op.create_index("ix_receipt_applications_invoice_external_id", "receipt_applications", ["invoice_external_id"])

    _create_scoped_table(
        "credit_memos",
        sa.Column("customer_external_id", sa.String(128), nullable=False),
        sa.Column("invoice_external_id", sa.String(128), nullable=True),
        sa.Column("currency", sa.String(3), nullable=False),
        sa.Column("credit_amount", MONEY, nullable=False),
        sa.Column("status", sa.String(32), nullable=False),
    )
    op.create_index("ix_credit_memos_customer_external_id", "credit_memos", ["customer_external_id"])

    _create_scoped_table(
        "credit_applications",
        sa.Column("credit_memo_external_id", sa.String(128), nullable=False),
        sa.Column("invoice_external_id", sa.String(128), nullable=False),
        sa.Column("applied_amount", MONEY, nullable=False),
        sa.Column("application_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(32), nullable=False),
    )
    op.create_index("ix_credit_applications_credit_memo_external_id", "credit_applications", ["credit_memo_external_id"])
    op.create_index("ix_credit_applications_invoice_external_id", "credit_applications", ["invoice_external_id"])

    _create_scoped_table(
        "disputes",
        sa.Column("invoice_external_id", sa.String(128), nullable=False),
        sa.Column("disputed_amount", MONEY, nullable=False),
        sa.Column("reason", sa.String(256), nullable=False),
        sa.Column("status", sa.String(32), nullable=False),
        sa.Column("opened_date", sa.Date(), nullable=False),
        sa.Column("closed_date", sa.Date(), nullable=True),
    )
    op.create_index("ix_disputes_invoice_external_id", "disputes", ["invoice_external_id"])

    _create_scoped_table(
        "order_holds",
        sa.Column("order_external_id", sa.String(128), nullable=False),
        sa.Column("hold_reason", sa.String(128), nullable=False),
        sa.Column("status", sa.String(32), nullable=False),
        sa.Column("applied_date", sa.Date(), nullable=False),
        sa.Column("released_date", sa.Date(), nullable=True),
        sa.Column("linked_invoice_external_id", sa.String(128), nullable=True),
    )
    op.create_index("ix_order_holds_order_external_id", "order_holds", ["order_external_id"])


def downgrade() -> None:
    op.drop_table("order_holds")
    op.drop_table("disputes")
    op.drop_table("credit_applications")
    op.drop_table("credit_memos")
    op.drop_table("receipt_applications")
    op.drop_table("receipts")
    op.drop_table("invoice_lines")
    op.drop_table("invoices")
    op.drop_table("shipment_lines")
    op.drop_table("shipments")
    op.drop_table("order_lines")
    op.drop_table("orders")
    op.drop_table("customers")
    op.drop_table("audit_events")
    op.drop_table("import_job_files")
    op.drop_constraint("fk_import_jobs_activated_dataset_version_id", "import_jobs", type_="foreignkey")
    op.drop_table("dataset_versions")
    op.drop_table("import_jobs")
    op.drop_table("user_business_unit_grants")
    op.drop_table("app_users")
    op.drop_table("business_units")
    op.drop_table("organizations")
