"""add snapshot_date to import_jobs

Revision ID: db132a94c6a0
Revises: 8a9f75265128
Create Date: 2026-10-02 18:57:14.018913

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'db132a94c6a0'
down_revision: str | Sequence[str] | None = '8a9f75265128'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('app_users_oidc_subject_key'), 'app_users', type_='unique')
    op.drop_index(op.f('ix_app_users_oidc_subject'), table_name='app_users')
    op.create_index(op.f('ix_app_users_oidc_subject'), 'app_users', ['oidc_subject'], unique=True)
    op.create_index(
        op.f('ix_credit_memos_invoice_external_id'), 'credit_memos', ['invoice_external_id'], unique=False
    )
    op.add_column('import_jobs', sa.Column('snapshot_date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('import_jobs', 'snapshot_date')
    op.drop_index(op.f('ix_credit_memos_invoice_external_id'), table_name='credit_memos')
    op.drop_index(op.f('ix_app_users_oidc_subject'), table_name='app_users')
    op.create_index(op.f('ix_app_users_oidc_subject'), 'app_users', ['oidc_subject'], unique=False)
    op.create_unique_constraint(op.f('app_users_oidc_subject_key'), 'app_users', ['oidc_subject'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
