"""add follow-up tasks and comments

Revision ID: e85aa0753f3f
Revises: db132a94c6a0
Create Date: 2026-10-02 19:32:57.328906

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e85aa0753f3f'
down_revision: str | Sequence[str] | None = 'db132a94c6a0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow_up_tasks',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('business_unit_id', sa.UUID(), nullable=False),
    sa.Column('dataset_version_id', sa.UUID(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('assignee_user_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('related_record_type', sa.String(length=64), nullable=True),
    sa.Column('related_record_id', sa.String(length=128), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignee_user_id'], ['app_users.id'], ),
    sa.ForeignKeyConstraint(['business_unit_id'], ['business_units.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['app_users.id'], ),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_versions.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_follow_up_tasks_business_unit_id'), 'follow_up_tasks', ['business_unit_id'], unique=False)
    op.create_index(op.f('ix_follow_up_tasks_organization_id'), 'follow_up_tasks', ['organization_id'], unique=False)
    op.create_table('task_comments',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('author_user_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['app_users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['follow_up_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_comments_task_id'), 'task_comments', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_comments_task_id'), table_name='task_comments')
    op.drop_table('task_comments')
    op.drop_index(op.f('ix_follow_up_tasks_organization_id'), table_name='follow_up_tasks')
    op.drop_index(op.f('ix_follow_up_tasks_business_unit_id'), table_name='follow_up_tasks')
    op.drop_table('follow_up_tasks')
    # ### end Alembic commands ###
